### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [5]:
a = np.array([1,2,3])
print(a)   


[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get Dimension
# a.ndim
b.ndim

2

In [12]:
# Get Shape
#a.shape
b.shape

(2, 3)

In [32]:
# Get Type
a.dtype

dtype('int32')

In [13]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [18]:
# Get Size
a.itemsize
#b.itemsize
# a.size

2

In [21]:
# Get total size
# a.size * a.itemsize
a.nbytes

6

In [35]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# Get a specific element [r, c]
a[0, 0]

1

In [32]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [42]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [44]:
a[1,5] =25
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 25 14]]


In [47]:
# a[:,3] = 5
# print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  1  5  5  6  7]
 [ 8  9  2  5 12 25 14]]


###### 3-d example

In [66]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [67]:
# Get specific element (work outside in)
b[1,1,1]

8

In [68]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [69]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [70]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [71]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
# All 1s matrix
# np.ones(4,2,2)
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

## Any other number
np.full((2,2), 99)
# np.full((2,2), 99, dtype = float32)

In [94]:
# Any other number (full_like)
np.full_like(a, 4)

array([4, 4, 4])

In [95]:
# Random decimal numbers
np.random.rand(4,2)
# np.random.randomsample(a.shape)

array([[0.77906656, 0.07894519],
       [0.27561679, 0.09540053],
       [0.51069646, 0.69867631],
       [0.07593846, 0.98997621]])

In [96]:
# Random Integer values
# np.random.randint(7)
np.random.randint(-4,8, size=(3,3))

array([[ 6,  0, -2],
       [ 1, -4,  0],
       [ 2,  3, -3]])

In [97]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [110]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [137]:
# output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [155]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)

[100   2   3]


### Mathematics

In [157]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [158]:
a + 2

array([3, 4, 5, 6])

In [159]:
a - 2

array([-1,  0,  1,  2])

In [160]:
a * 2

array([2, 4, 6, 8])

In [161]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [162]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [163]:
a ** 2

array([ 1,  4,  9, 16])

In [167]:
# Take the sin
np.sin(a)



array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [165]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [133]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [168]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [135]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [170]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
np.min(stats)

1

In [172]:
np.max(stats, axis=1)

array([3, 6])

In [173]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [174]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
# after = before.reshape((4,2))
# after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [175]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [176]:
filedata = np.genfromtxt('data.txt', delimiter=',')
# filedata = filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


##### Boolean Masking and Advanced Indexing

In [178]:
filedata < 50

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [179]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [180]:
# you can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

array([2, 3, 9])

In [181]:
# any value along all the columns is greater than 50
np.any(filedata>50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [182]:
# when all values along the columns are greater than 50
np.all(filedata>50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [9]:
# all the values that are greater than 50 but less than 100
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [196]:
# reverse of above
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [82]:
# !pip install nbconvert

In [83]:
# !pip install pyppeteer

In [87]:
# !pip install jinja2==3.0.3